version: '3'
services:
  backend-app:
    image: backend-app:latest
    ports:
      - '3001:3001'
    env_file:
      - .env.backend
  frontend-app:
    image: frontend-app:latest
    ports:
      - '3000:3000'
    env_file:
      - .env.frontend
